[{"ContainerToolsException.Message":"Visual Studio Container Tools requires Docker to be running before building, debugging or running a containerized project.  For more info, please see: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [15523] Failed to execute script docker-compose\nIf the error persists, try restarting Docker Desktop.\n ---> Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: [15523] Failed to execute script docker-compose\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\nError code: DT1001\nSeverity: Error\nCommand line: docker-compose  -f \"/Users/maryambakht/Documents/maryam/EagleRock /docker-compose.yml\" -f \"/Users/maryambakht/Documents/maryam/EagleRock /docker-compose.override.yml\" -f \"/Users/maryambakht/Documents/maryam/EagleRock /obj/Docker/docker-compose.vs.debug.g.yml\" -p dockercompose7456397001548253376 --ansi never up -d --build --remove-orphans\nCommand exit code: 255\nCommand output: \nCommand error: Traceback (most recent call last):\n  File \"urllib3/connectionpool.py\", line 670, in urlopen\n  File \"urllib3/connectionpool.py\", line 392, in _make_request\n  File \"http/client.py\", line 1255, in request\n  File \"http/client.py\", line 1301, in _send_request\n  File \"http/client.py\", line 1250, in endheaders\n  File \"http/client.py\", line 1010, in _send_output\n  File \"http/client.py\", line 950, in send\n  File \"docker/transport/unixconn.py\", line 43, in connect\nConnectionRefusedError: [Errno 61] Connection refused\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"requests/adapters.py\", line 439, in send\n  File \"urllib3/connectionpool.py\", line 726, in urlopen\n  File \"urllib3/util/retry.py\", line 410, in increment\n  File \"urllib3/packages/six.py\", line 734, in reraise\n  File \"urllib3/connectionpool.py\", line 670, in urlopen\n  File \"urllib3/connectionpool.py\", line 392, in _make_request\n  File \"http/client.py\", line 1255, in request\n  File \"http/client.py\", line 1301, in _send_request\n  File \"http/client.py\", line 1250, in endheaders\n  File \"http/client.py\", line 1010, in _send_output\n  File \"http/client.py\", line 950, in send\n  File \"docker/transport/unixconn.py\", line 43, in connect\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"docker/api/client.py\", line 214, in _retrieve_server_version\n  File \"docker/api/daemon.py\", line 181, in version\n  File \"docker/utils/decorators.py\", line 46, in inner\n  File \"docker/api/client.py\", line 237, in _get\n  File \"requests/sessions.py\", line 543, in get\n  File \"requests/sessions.py\", line 530, in request\n  File \"requests/sessions.py\", line 643, in send\n  File \"requests/adapters.py\", line 498, in send\nrequests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))\nDuring handling of the above exception, another exception occurred:\nTraceback (most recent call last):\n  File \"docker-compose\", line 3, in <module>\n  File \"compose/cli/main.py\", line 81, in main\n  File \"compose/cli/main.py\", line 200, in perform_command\n  File \"compose/cli/command.py\", line 60, in project_from_options\n  File \"compose/cli/command.py\", line 152, in get_project\n  File \"compose/cli/docker_client.py\", line 41, in get_client\n  File \"compose/cli/docker_client.py\", line 170, in docker_client\n  File \"docker/api/client.py\", line 197, in __init__\n  File \"docker/api/client.py\", line 221, in _retrieve_server_version\ndocker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))\n[15523] Failed to execute script docker-compose\n\n   --- End of inner exception stack trace ---\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\n   at Microsoft.Docker.BuildTasks.PrepareForLaunch.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)\nError code: DT1001\nSeverity: Error\n"}]